//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Levels
{ 

public sealed partial class TBLevel
{
    private readonly Dictionary<int, Levels.Level> _dataMap;
    private readonly List<Levels.Level> _dataList;
    
    public TBLevel(JSONNode _json)
    {
        _dataMap = new Dictionary<int, Levels.Level>();
        _dataList = new List<Levels.Level>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Levels.Level.DeserializeLevel(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Levels.Level> DataMap => _dataMap;
    public List<Levels.Level> DataList => _dataList;

    public Levels.Level GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Levels.Level Get(int key) => _dataMap[key];
    public Levels.Level this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}