//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.Hero
{ 

public sealed partial class HeroInfo :  Bright.Config.BeanBase 
{
    public HeroInfo(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { if(!_json["heroMaxLevel"].IsNumber) { throw new SerializationException(); }  HeroMaxLevel = _json["heroMaxLevel"]; }
        { if(!_json["hp"].IsNumber) { throw new SerializationException(); }  Hp = _json["hp"]; }
        { if(!_json["attack"].IsNumber) { throw new SerializationException(); }  Attack = _json["attack"]; }
        PostInit();
    }

    public HeroInfo(int id, string name, int heroMaxLevel, int hp, float attack ) 
    {
        this.Id = id;
        this.Name = name;
        this.HeroMaxLevel = heroMaxLevel;
        this.Hp = hp;
        this.Attack = attack;
        PostInit();
    }

    public static HeroInfo DeserializeHeroInfo(JSONNode _json)
    {
        return new Hero.HeroInfo(_json);
    }

    public int Id { get; private set; }
    public string Name { get; private set; }
    public int HeroMaxLevel { get; private set; }
    public int Hp { get; private set; }
    public float Attack { get; private set; }

    public const int __ID__ = -623039684;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "HeroMaxLevel:" + HeroMaxLevel + ","
        + "Hp:" + Hp + ","
        + "Attack:" + Attack + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
