//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Hero
{
public sealed partial class HeroInfo :  Bright.Config.BeanBase 
{
    public HeroInfo(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        HeroMaxLevel = _buf.ReadInt();
        Hp = _buf.ReadInt();
        Attack = _buf.ReadFloat();
        PostInit();
    }

    public static HeroInfo DeserializeHeroInfo(ByteBuf _buf)
    {
        return new Hero.HeroInfo(_buf);
    }

    public int Id { get; private set; }
    public string Name { get; private set; }
    public int HeroMaxLevel { get; private set; }
    public int Hp { get; private set; }
    public float Attack { get; private set; }

    public const int __ID__ = -623039684;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "HeroMaxLevel:" + HeroMaxLevel + ","
        + "Hp:" + Hp + ","
        + "Attack:" + Attack + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}